version: '3'
services:
  mysql:
    image: mysql:latest
    network_mode: bridge
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    image: redis:latest
    network_mode: bridge
    #    environment:
    #      - REDIS_PASSWORD=123456
    ports:
      - 6379:6379

  rabbitmq:
    image: rabbitmq:latest
    network_mode: bridge
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=123
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  minio:
    image: quay.io/minio/minio
    network_mode: bridge
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - /mnt/data1:/data1
      - /mnt/data2:/data2
      - /mnt/data3:/data3
      - /mnt/data4:/data4
      - /mnt/data5:/data5
      - /mnt/data6:/data6
      - /mnt/data7:/data7
      - /mnt/data8:/data8
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
    command: server /data{1...8} --console-address ":9090"

networks:
  buzzwaves-network:
    external: true